import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#ques1
#a)
a=pd.read_csv("employees.csv")
print(a.info())
print("First five rows of dataset: \n",a.head())
#b)
print("Column names: \n",a.columns)
print("Data types: \n",a.dtypes)
print("Shape of dataset: \n",a.shape)
#c)
s=pd.Series(a['Salary'])
print("Mean of Salary column: ",s.mean())
print("Minimum Salary: ",s.min())
print("Maximum Salary: ",s.max())
#d)
print(a.isnull().sum())
b=a['Team'].fillna('Unknown')
print(b.head())
#e)
plt.figure()
sns.countplot(x="Team",data=a)
plt.title("No of Employees in each team")
plt.show()

#ques2
#a)
titanic = sns.load_dataset("titanic")
print(titanic.info())
#b)
print("First ten rows: \n",titanic.head(10))
print("Shape of dataset: \n",titanic.shape)
print("Column datatypes: \n",titanic.dtypes)
#c)
c= titanic.groupby('sex')['survived'].mean()
print(c)
plt.figure()
plt.bar(c.index,c.values)
plt.title("Male vs Female Survival rate")
plt.xlabel("Sex")
plt.ylabel("Survived")
plt.show()
#d)
d= titanic.groupby('class')['survived'].sum()
print(d)
plt.figure()
plt.bar(d.index,d.values)
plt.title("Passenger class Survival rate")
plt.xlabel("Passengers")
plt.ylabel("Survived")
plt.show()
#e)
e= titanic.groupby('alive')['fare'].mean()
print(e)

